### ISSUE TITLE
What about negative temperatures, (e.g. blow freezing)?

### ISSUE THREAD

**Issue by hk-on-github** [angrest/pocketBME280#11]
The method uint32_t getTemperature(void); reports an unsigned value. How would I get temperatures below 0 C from my sensor? Or do I overlook or misunderstand something?

**Comment by angrest** [comment]
Thank you for pointing this out - indeed a bug. It should be a signed integer, of course.

**Comment by angrest** [comment]
fixed in [v1.2.2 ](https://github.com/angrest/pocketBME280/releases/tag/v1.2.2)- should appear shortly in Arduino library manager or can be downloaded directly here.
